// when mocking xhr requests, make sure to use a function that
// returns your expected response. if you don't, it's too easy
// to end up with reference errors that are a pain to debug.

// date: 2018-02-25
// endpoint: https://api.github.com/repos/scottbedard/oc-vuetober-theme
export function fetchRepositoryFixture() {
    return {
        id: 49362717,
        name: "oc-vuetober-theme",
        full_name: "scottbedard/oc-vuetober-theme",
        owner: {
            login: "scottbedard",
            id: 7980426,
            avatar_url: "https://avatars2.githubusercontent.com/u/7980426?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/scottbedard",
            html_url: "https://github.com/scottbedard",
            followers_url: "https://api.github.com/users/scottbedard/followers",
            following_url: "https://api.github.com/users/scottbedard/following{/other_user}",
            gists_url: "https://api.github.com/users/scottbedard/gists{/gist_id}",
            starred_url: "https://api.github.com/users/scottbedard/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/scottbedard/subscriptions",
            organizations_url: "https://api.github.com/users/scottbedard/orgs",
            repos_url: "https://api.github.com/users/scottbedard/repos",
            events_url: "https://api.github.com/users/scottbedard/events{/privacy}",
            received_events_url: "https://api.github.com/users/scottbedard/received_events",
            type: "User",
            site_admin: false,
        },
        private: false,
        html_url: "https://github.com/scottbedard/oc-vuetober-theme",
        description: "Built single page apps with October CMS and Vue",
        fork: false,
        url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme",
        forks_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/forks",
        keys_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/keys{/key_id}",
        collaborators_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/collaborators{/collaborator}",
        teams_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/teams",
        hooks_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/hooks",
        issue_events_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/issues/events{/number}",
        events_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/events",
        assignees_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/assignees{/user}",
        branches_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/branches{/branch}",
        tags_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/tags",
        blobs_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/git/blobs{/sha}",
        git_tags_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/git/tags{/sha}",
        git_refs_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/git/refs{/sha}",
        trees_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/git/trees{/sha}",
        statuses_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/statuses/{sha}",
        languages_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/languages",
        stargazers_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/stargazers",
        contributors_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/contributors",
        subscribers_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/subscribers",
        subscription_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/subscription",
        commits_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/commits{/sha}",
        git_commits_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/git/commits{/sha}",
        comments_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/comments{/number}",
        issue_comment_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/issues/comments{/number}",
        contents_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/contents/{+path}",
        compare_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/compare/{base}...{head}",
        merges_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/merges",
        archive_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/{archive_format}{/ref}",
        downloads_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/downloads",
        issues_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/issues{/number}",
        pulls_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/pulls{/number}",
        milestones_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/milestones{/number}",
        notifications_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/notifications{?since,all,participating}",
        labels_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/labels{/name}",
        releases_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/releases{/id}",
        deployments_url: "https://api.github.com/repos/scottbedard/oc-vuetober-theme/deployments",
        created_at: "2016-01-10T10:41:30Z",
        updated_at: "2018-02-22T21:53:47Z",
        pushed_at: "2018-02-25T19:22:24Z",
        git_url: "git://github.com/scottbedard/oc-vuetober-theme.git",
        ssh_url: "git@github.com:scottbedard/oc-vuetober-theme.git",
        clone_url: "https://github.com/scottbedard/oc-vuetober-theme.git",
        svn_url: "https://github.com/scottbedard/oc-vuetober-theme",
        homepage: "http://vuetober.scottbedard.net",
        size: 1067,
        stargazers_count: 164,
        watchers_count: 164,
        language: "JavaScript",
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 27,
        mirror_url: null,
        archived: false,
        open_issues_count: 3,
        license: {
            key: "mit",
            name: "MIT License",
            spdx_id: "MIT",
            url: "https://api.github.com/licenses/mit",
        },
        forks: 27,
        open_issues: 3,
        watchers: 164,
        default_branch: "master",
        network_count: 27,
        subscribers_count: 14,
    };
}
